/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package c1_precentacion;

import c2_aplicacion.GestionarAreaServicio;
import c2_aplicacion.GestionarAutorizanteServicio;
import c2_aplicacion.GestionarMovimientoServicio;
import c3_dominio.Area;
import c3_dominio.LoginUser;
import c3_dominio.Movimiento;
import c3_dominio.Producto;
import c3_dominio.Autorizante; 
import c3_dominio.DetalleMovimiento;
import config.MyConfig;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Franz
 */
public class FormGestionarSalidaArticulo extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormGestionarUnidad
     */
    private String flag = "Guardar";
    private String tempMovimiento_id;
    private boolean rem = false;
    Movimiento movimiento;
    Producto producto;
    public static Producto tempProducto;
    public static Autorizante tempAutorizante;
    private GestionarMovimientoServicio gu;
    private List<Movimiento> movimientos;
    private List<Movimiento> templist = new ArrayList();
    private List<DetalleMovimiento> tempObj = new ArrayList(); 
    private final LoginUser user = LoginUser.getInstancia();
    private boolean reporte = false;

    public FormGestionarSalidaArticulo(java.awt.Frame parent, boolean modal) {
        initComponents();
        lblPersonal.setText(user.getPersonal().getNombre() + " " + user.getPersonal().getApellidoPaterno() + " " + user.getPersonal().getApellidoMaterno());
        mostrar(tempObj);
        cargarAutorizante();
        cargarArea();
        botones(false);
        btnReporte.setEnabled(false);
        lblId.setVisible(false);
        lblIdArticulo.setVisible(false);
        lblindiceselect.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        table1 = new javax.swing.JTabbedPane();
        panel1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblPersonal = new javax.swing.JLabel();
        lblIdArticulo = new javax.swing.JLabel();
        lblindiceselect = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtSolicitante = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtAsunto = new javax.swing.JTextField();
        txtReferencia = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        lblSolicitante = new javax.swing.JLabel();
        cboAutorizante = new javax.swing.JComboBox();
        txtNumSalida = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        cboArea = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCabecera = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        txtNumExpediente = new javax.swing.JTextField();
        txtNumDocumento = new javax.swing.JTextField();
        panel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listado = new javax.swing.JTable();
        jLabel64 = new javax.swing.JLabel();
        txtCodUnt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        txtCodSaneamiento = new javax.swing.JTextField();
        btnAddArticulo = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnRemoveArticulo = new javax.swing.JButton();
        lblProductoCantidad = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtObservacion = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        btnBuscarArticulo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblArticulo = new javax.swing.JLabel();
        testoplano = new javax.swing.JLabel();
        lblCodigoProducto = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jspCantidad = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSerie = new javax.swing.JTextField();
        txtUnidad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lblNumRegistro = new javax.swing.JLabel();
        btnReporte = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Salida de Productos de Almacen");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion General"));

        lblId.setText("id");

        jLabel2.setText("Nº MEMO :");

        jLabel7.setText("Encargado : ");

        lblPersonal.setText("Personal");

        lblIdArticulo.setText("idarticulo");

        lblindiceselect.setText("indiceselect");

        jLabel3.setText("Nº Expediente :");

        jLabel5.setText("Nº Documento :");

        jLabel13.setText("Asunto : ");

        jLabel14.setText("Solicitante :");

        jLabel15.setText("Referencia :");

        lblSolicitante.setText("Del :");

        try {
            txtNumSalida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel18.setText("Seccion  :");

        txtCabecera.setColumns(20);
        txtCabecera.setLineWrap(true);
        txtCabecera.setRows(5);
        jScrollPane1.setViewportView(txtCabecera);

        jLabel19.setText("Cabecera : ");

        txtNumExpediente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumExpedienteKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(lblId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblIdArticulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblindiceselect))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(jLabel17)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtReferencia))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(lblSolicitante))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboAutorizante, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSolicitante)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txtNumSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblPersonal)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel18))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cboArea, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtAsunto))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(lblIdArticulo)
                    .addComponent(lblindiceselect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblPersonal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(txtNumSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSolicitante)
                    .addComponent(cboAutorizante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cboArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(txtAsunto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addContainerGap())
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, Short.MAX_VALUE)
                .addContainerGap())
        );

        table1.addTab("Cabecera", panel1);

        listado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listadoMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(listado);

        jLabel64.setText("Codigo Unt :");

        jLabel10.setText("Color :");

        jLabel65.setText("Cod Sanea.  :");

        btnAddArticulo.setText("Agregar Producto");
        btnAddArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddArticuloActionPerformed(evt);
            }
        });

        jLabel11.setText("Cant :");

        btnRemoveArticulo.setText("Quitar Articulo");
        btnRemoveArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveArticuloActionPerformed(evt);
            }
        });

        lblProductoCantidad.setText("000");

        jLabel12.setText("Observacion :");

        txtObservacion.setColumns(20);
        txtObservacion.setLineWrap(true);
        txtObservacion.setRows(5);
        jScrollPane3.setViewportView(txtObservacion);

        jLabel1.setText("Producto :");

        jLabel16.setText("Modelo :");

        btnBuscarArticulo.setText("...");
        btnBuscarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarArticuloActionPerformed(evt);
            }
        });

        jLabel4.setText("Articulo : ");

        lblArticulo.setText("Producto");

        testoplano.setText("Cod :");

        lblCodigoProducto.setText("000");

        jLabel6.setText("Cantidad :");

        jLabel21.setText("Nº serie : ");

        jLabel8.setText("Unidad :");

        jLabel9.setText("Marca :");

        lblNumRegistro.setText("Nº Registros");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(btnAddArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnRemoveArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addGap(58, 58, 58)
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCodUnt, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                    .addComponent(txtColor))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(10, 10, 10)
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3)
                                    .addGroup(panel2Layout.createSequentialGroup()
                                        .addComponent(btnBuscarArticulo)
                                        .addGap(6, 6, 6)
                                        .addComponent(testoplano)
                                        .addGap(3, 3, 3)
                                        .addComponent(lblCodigoProducto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblProductoCantidad)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblArticulo)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(panel2Layout.createSequentialGroup()
                                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)
                                        .addGap(49, 49, 49)
                                        .addComponent(txtUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jspCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addComponent(lblNumRegistro)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel2Layout.createSequentialGroup()
                                        .addGap(88, 88, 88)
                                        .addComponent(txtSerie))
                                    .addGroup(panel2Layout.createSequentialGroup()
                                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel21))
                                        .addGap(185, 185, 185)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel64))
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addComponent(jLabel65)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCodSaneamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBuscarArticulo)
                    .addComponent(jLabel4)
                    .addComponent(lblArticulo)
                    .addComponent(testoplano)
                    .addComponent(lblCodigoProducto)
                    .addComponent(jLabel11)
                    .addComponent(lblProductoCantidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jspCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel64)
                    .addComponent(txtCodUnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel65)
                    .addComponent(txtCodSaneamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddArticulo)
                    .addComponent(btnRemoveArticulo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNumRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        table1.addTab("Agregar Productos", panel2);

        btnReporte.setText("Generar Reporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(btnNuevo)
                        .addGap(29, 29, 29)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(table1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(table1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar)
                    .addComponent(btnReporte))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiar() {
        lblId.setText("id");
        lblIdArticulo.setText("idarticulo");
        lblindiceselect.setText("indiceselect");
        txtNumSalida.setText("");
        txtNumExpediente.setText("");
        txtNumDocumento.setText("");
        txtSolicitante.setText("");
        lblSolicitante.setText("nombre");
        txtAsunto.setText("");
        txtReferencia.setText("");
        txtCabecera.setText("");
        cboAutorizante.setSelectedIndex(0);
        cboArea.setSelectedIndex(0);
        limpiaradd();
        txtNumSalida.setText("");
        txtNumSalida.requestFocus();
        templist = new ArrayList();
        mostrar(tempObj);

    }

    private void limpiaradd() {
        lblCodigoProducto.setText("000");
        lblProductoCantidad.setText("000");
        lblArticulo.setText("Producto");
        txtObservacion.setText("");
        txtModelo.setText("");
        txtUnidad.setText("");
        txtMarca.setText("");
        txtColor.setText("");
        txtSerie.setText("");
        txtCodUnt.setText("");
        txtCodSaneamiento.setText("");
        jspCantidad.setValue(0);
    }

    private void botones(boolean btn) {
        txtNumSalida.setEnabled(btn);
        txtNumSalida.setEnabled(btn);
        txtNumExpediente.setEnabled(btn);
        txtNumDocumento.setEnabled(btn);
        txtSolicitante.setEnabled(btn);
        txtAsunto.setEnabled(btn);
        txtReferencia.setEnabled(btn);
        txtCabecera.setEnabled(btn);
        txtObservacion.setEnabled(btn);
        txtUnidad.setEnabled(btn);
        txtMarca.setEnabled(btn);
        txtColor.setEnabled(btn);
        jspCantidad.setEnabled(btn);
        txtModelo.setEnabled(btn);
        txtSerie.setEnabled(btn);
        txtCodUnt.setEnabled(btn);
        txtCodSaneamiento.setEnabled(btn);
        cboAutorizante.setEnabled(btn);
        cboArea.setEnabled(btn);
        btnCancelar.setEnabled(btn);
        btnNuevo.setEnabled(!btn);
        btnBuscarArticulo.setEnabled(btn);
        btnAddArticulo.setEnabled(btn);
        btnRemoveArticulo.setEnabled(btn);
        btnGuardar.setEnabled(btn);
        btnReporte.setEnabled(!btn);

    }

    private void cargarAutorizante() {
        GestionarAutorizanteServicio guc = new GestionarAutorizanteServicio();
        try {
            for (Autorizante aut : guc.listar()) {
                cboAutorizante.addItem(aut.getDescripcion());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    private void cargarArea() {
        GestionarAreaServicio gas = new GestionarAreaServicio();
        try {
            for (Area obj : gas.listar()) {
                cboArea.addItem(obj.getDescripcion());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    private void mostrar(List<DetalleMovimiento> movimientos) {
        try {
            gu = new GestionarMovimientoServicio();
            gu.llenarLista(listado, movimientos);
            lblNumRegistro.setText("Nº Registros : " + String.valueOf(listado.getRowCount()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }


    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String salida = txtNumSalida.getText().trim();
        String exp = txtNumExpediente.getText().trim();
        String doc = txtNumDocumento.getText().trim();
        movimiento = new Movimiento();     

        int i = 0;
        if (!salida.equals("")) {
            if (MyConfig.validarInt(salida)) {
                if (MyConfig.validarTamanio(salida, 4)) {
                    if (!exp.equals("")) {
                        if (MyConfig.validarTamanio(exp, 15)) {
                            if (MyConfig.validarInt(exp)) {
                                if (!doc.equals("")) {
                                    if (MyConfig.validarTamanio(doc, 15)) {
                                        if (MyConfig.validarInt(doc)) {
                                            if (tempObj.size() >= 1) {
                                                try {
                                                    gu = new GestionarMovimientoServicio();
                                                    movimiento.setOperacion("salida");
                                                    Calendar calendar = Calendar.getInstance();
                                                    Timestamp fecha = new Timestamp(calendar.getTime().getTime());
                                                    movimiento.setFechaRegistro(fecha);
                                                    movimiento.setNumSalida(MyConfig.getGenerarCodigo(txtNumSalida.getText().toUpperCase().trim()));
                                                    tempMovimiento_id = MyConfig.getGenerarCodigo(txtNumSalida.getText().toUpperCase().trim());
                                                    movimiento.setNumExpediente(txtNumExpediente.getText().trim());
                                                    movimiento.setNumDocumento(txtNumDocumento.getText().trim());
                                                    movimiento.setAsunto(txtAsunto.getText().trim());
                                                    movimiento.setSolicitante(txtSolicitante.getText().trim());
                                                    GestionarAreaServicio gars = new GestionarAreaServicio();
                                                    movimiento.setArea(gars.obtenerId(gars.listar(), cboArea.getSelectedItem().toString()));
                                                    GestionarAutorizanteServicio gas = new GestionarAutorizanteServicio();
                                                    movimiento.setAutorizante(gas.obtenerId(gas.listar(), cboAutorizante.getSelectedItem().toString()));
                                                    movimiento.setReferencia(txtReferencia.getText().trim());
                                                    movimiento.setPersonal(user.getPersonal());
                                                    movimiento.setCabecera(txtCabecera.getText());

                                                    if (flag.equals("Guardar")) {
                                                        if(gu.insertarSalida(movimiento,tempObj)){
                                                             JOptionPane.showMessageDialog(null, "Guardar");
                                                                    botones(false);
                                                                    btnReporte.setEnabled(true);
                                                                    reporte = true;
                                                        }else{
                                                             JOptionPane.showMessageDialog(null, "No se pudo guardar");
                                                        }
//                                                        System.out.println("cont " + templist.size());
//                                                        for (Movimiento dts : templist) {
//                                                            if (gu.insertarSalida(dts)) {
//                                                                i++;
//                                                                gu.removeCantidad(dts);
//                                                                if (i == templist.size()) {
//                                                                    JOptionPane.showMessageDialog(null, "Guardar");
//                                                                    botones(false);
//                                                                    btnReporte.setEnabled(true);
//                                                                    reporte = true;
//                                                                }
//                                                            } else {
//                                                                JOptionPane.showMessageDialog(null, "No se pudo guardar");
//                                                            }
//                                                        }
                                                    }
                                                } catch (Exception e) {
                                                    JOptionPane.showMessageDialog(null, e);
                                                }
                                            } else {
                                                JOptionPane.showMessageDialog(this, "Debe Seleccionar almenos un articulo", "Aviso", 0);
                                            }
                                        } else {
                                            JOptionPane.showMessageDialog(this, "Solo se acepta Numeros en Documento", "Aviso", 0);
                                            txtNumDocumento.requestFocus();
                                        }
                                    } else {
                                        JOptionPane.showMessageDialog(this, "Solo se acepta 15 digitos en Documento", "Aviso", 0);
                                        txtNumDocumento.requestFocus();
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(this, "Debe ingresar un numero de Documento", "Aviso", 0);
                                    txtNumDocumento.requestFocus();
                                }
                            } else {
                                JOptionPane.showMessageDialog(this, "Solo Se Acepta Numeros En Expediente", "Aviso", 0);
                                txtNumExpediente.requestFocus();
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "Solo se acepta 15 digitos en Expediente", "Aviso", 0);
                            txtNumExpediente.requestFocus();
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Debe ingresar un numero de Expediente", "Aviso", 0);
                        txtNumExpediente.requestFocus();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Solo se acepta 4 digitos", "Aviso", 0);
                    txtNumSalida.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Solo se Acepta Numeros en La Salida", "Aviso", 0);
                txtNumSalida.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe ingresar un numero de Salida", "Aviso", 0);
            txtNumSalida.requestFocus();
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiar();
        botones(false);
        btnGuardar.setText("Guardar");
        flag = "Guardar";

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiar();
        botones(true);
        btnGuardar.setText("Guardar");
        flag = "Guardar";
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void listadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadoMouseClicked
        int fila = listado.rowAtPoint(evt.getPoint());
        lblIdArticulo.setText(listado.getValueAt(fila, 0).toString());
        jspCantidad.setValue(Integer.parseInt(listado.getValueAt(fila, 1).toString()));
        lblCodigoProducto.setText(listado.getValueAt(fila, 2).toString());
        lblArticulo.setText(listado.getValueAt(fila, 3).toString());
        lblindiceselect.setText(String.valueOf(listado.getSelectedRow()));
        this.rem = true;
    }//GEN-LAST:event_listadoMouseClicked

    private void btnAddArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddArticuloActionPerformed
        DetalleMovimiento detalle = new DetalleMovimiento();
        try {
            if (!lblCodigoProducto.getText().equals("000")) {
                if (tempProducto.getCantidad() > 0) {
                    if (Integer.parseInt(jspCantidad.getValue().toString()) > 0) {
                        if (Integer.parseInt(jspCantidad.getValue().toString()) <= tempProducto.getCantidad()) {
                            detalle.setCantidad(Integer.parseInt(jspCantidad.getValue().toString()));
                            detalle.setNumSerie(txtSerie.getText().trim());
                            detalle.setCodigoUnt(txtCodUnt.getText().trim());
                            detalle.setCodigoSaneamiento(txtCodSaneamiento.getText().trim());
                            detalle.setObservacion(txtObservacion.getText().trim());
                            detalle.setProducto(tempProducto);
                            tempObj.add(detalle);
                            mostrar(tempObj);
                            limpiaradd();
                        } else {
                            JOptionPane.showMessageDialog(null, "La cantidad supera al stock actual del producto", "aviso", 2);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "la cantidad minima debe ser 1", "aviso", 2);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El producto no cuenta con stock", "aviso", 2);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Debe Seleccionar un articulo almenos", "aviso", 2);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnAddArticuloActionPerformed

    private void btnBuscarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarArticuloActionPerformed
        FormProductoListado form = new FormProductoListado(null, true, "salida");
        FormPrincipal.escritorio.add(form);
        form.toFront();
        tempProducto = new Producto();
        form.tempProducto = tempProducto;
        form.setVisible(true);
    }//GEN-LAST:event_btnBuscarArticuloActionPerformed

    private void listadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_listadoMousePressed

    private void btnRemoveArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveArticuloActionPerformed
        if (this.rem) {
            tempObj.remove(Integer.parseInt(lblindiceselect.getText()));
            mostrar(tempObj);
            limpiaradd();
            this.rem = false;
        } else {
            JOptionPane.showMessageDialog(null, "Debe Seleccionar un articulo de la lista", "aviso", 1);
        }
    }//GEN-LAST:event_btnRemoveArticuloActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        try {
            gu.reporteMemo(tempMovimiento_id);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnReporteActionPerformed

    private void txtNumExpedienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumExpedienteKeyPressed

    }//GEN-LAST:event_txtNumExpedienteKeyPressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddArticulo;
    private javax.swing.JButton btnBuscarArticulo;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRemoveArticulo;
    private javax.swing.JButton btnReporte;
    private javax.swing.JComboBox cboArea;
    private javax.swing.JComboBox cboAutorizante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jspCantidad;
    public static javax.swing.JLabel lblArticulo;
    public static javax.swing.JLabel lblCodigoProducto;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIdArticulo;
    private javax.swing.JLabel lblNumRegistro;
    private javax.swing.JLabel lblPersonal;
    public static javax.swing.JLabel lblProductoCantidad;
    public static javax.swing.JLabel lblSolicitante;
    private javax.swing.JLabel lblindiceselect;
    private javax.swing.JTable listado;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JTabbedPane table1;
    private javax.swing.JLabel testoplano;
    private javax.swing.JTextField txtAsunto;
    private javax.swing.JTextArea txtCabecera;
    private javax.swing.JTextField txtCodSaneamiento;
    private javax.swing.JTextField txtCodUnt;
    private javax.swing.JTextField txtColor;
    public static javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNumDocumento;
    private javax.swing.JTextField txtNumExpediente;
    private javax.swing.JFormattedTextField txtNumSalida;
    private javax.swing.JTextArea txtObservacion;
    private javax.swing.JTextField txtReferencia;
    private javax.swing.JTextField txtSerie;
    private javax.swing.JTextField txtSolicitante;
    public static javax.swing.JTextField txtUnidad;
    // End of variables declaration//GEN-END:variables
}
