/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package c1_precentacion;

import c2_aplicacion.GestionarAlmacenServicio;
import c2_aplicacion.GestionarCategoriaServicio;
import c2_aplicacion.GestionarMarcaServicio;
import c2_aplicacion.GestionarProductoServicio;
import c2_aplicacion.GestionarTipoProductoServicio;
import c2_aplicacion.GestionarUnidadServicio;
import c3_dominio.Almacen;
import c3_dominio.Categoria;
import c3_dominio.Marca;
import c3_dominio.Producto;
import c3_dominio.TipoPersonal;
import c3_dominio.TipoProducto;
import c3_dominio.Unidad;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.util.ArrayList;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import java.util.Date;
import java.util.Calendar;

/**
 *
 * @author Franz
 */
public class FormProductoListado extends javax.swing.JDialog {

    /**
     * Creates new form FormGestionarUnidad
     */
    private String flag = "principal";
    Producto producto;
    public Producto tempProducto;
    private GestionarProductoServicio gu;
    private List<Producto> productos;
    private String tipoForm;

    public FormProductoListado(String tipo) {       
        initComponents();
        mostrar("principal");
        tempProducto = new Producto();
        this.tipoForm = tipo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        listado = new javax.swing.JTable();
        lblNumRegistro = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnAddnewProduct = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        rbtPrincipal = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrador de Unidades");

        listado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listadoMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(listado);

        lblNumRegistro.setText("Nº Registros");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnAddnewProduct.setText("Agregar un producto");
        btnAddnewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddnewProductActionPerformed(evt);
            }
        });

        jLabel7.setText("Almacen :");

        buttonGroup1.add(rbtPrincipal);
        rbtPrincipal.setSelected(true);
        rbtPrincipal.setText("Principal");
        rbtPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbtPrincipalMousePressed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Sotano");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadioButton2MousePressed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Codigo", "Nombre" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(btnAddnewProduct)
                        .addGap(56, 56, 56)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNumRegistro)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtPrincipal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton2))
                            .addComponent(txtBuscar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rbtPrincipal)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNumRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddnewProduct)
                    .addComponent(btnSalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiar() {
        txtBuscar.setText("");

    }

    private void mostrar(String location) {
        try {
            gu = new GestionarProductoServicio();
            productos = gu.listar();
            productos = gu.listLocation(productos, location);
            gu.llenarLista(listado, productos);
            lblNumRegistro.setText("Nº Registros : " + String.valueOf(listado.getRowCount()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }


    private void btnAddnewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddnewProductActionPerformed
       FormGestionarProducto form = new FormGestionarProducto(null,false);
       form.setVisible(true);
    }//GEN-LAST:event_btnAddnewProductActionPerformed

    private void listadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadoMouseClicked

    }//GEN-LAST:event_listadoMouseClicked

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        gu = new GestionarProductoServicio();
        try {
            //unidad.setUnidad(String.valueOf(evt.getKeyChar()));   
            if (jComboBox1.getSelectedItem().equals("Codigo")) {
                productos = gu.searchItems(flag, txtBuscar.getText(), jComboBox1.getSelectedItem().toString());
                gu.llenarLista(listado, productos);
                lblNumRegistro.setText("Nº Registros : " + String.valueOf(listado.getRowCount()));
            } else {
                productos = gu.searchItems(flag, txtBuscar.getText(), jComboBox1.getSelectedItem().toString());
                gu.llenarLista(listado, productos);
                lblNumRegistro.setText("Nº Registros : " + String.valueOf(listado.getRowCount()));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void listadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadoMousePressed
        // TODO add your handling code here: 
        if (evt.getClickCount() == 2) {
            int fila = listado.getSelectedRow();
            tempProducto.setId(Integer.parseInt(listado.getValueAt(fila, 0).toString()));
            tempProducto.setCodigo(listado.getValueAt(fila, 1).toString());
            tempProducto.setArticulo(listado.getValueAt(fila, 2).toString());
            tempProducto.setCantidad(Integer.parseInt(listado.getValueAt(fila, 5).toString()));
            if (tipoForm.equals("ingreso")) {
                FormGestionarIngresoArticulo.lblCodigoProducto.setText(listado.getValueAt(fila, 1).toString());
                FormGestionarIngresoArticulo.lblArticulo.setText(listado.getValueAt(fila, 2).toString());
                FormGestionarIngresoArticulo.tempProducto = tempProducto;
                this.setVisible(false);
            } else if (tipoForm.equals("salida")) {
                FormGestionarSalidaArticulo.lblCodigoProducto.setText(listado.getValueAt(fila, 1).toString());
                FormGestionarSalidaArticulo.lblArticulo.setText(listado.getValueAt(fila, 2).toString());
                FormGestionarSalidaArticulo.lblProductoCantidad.setText(listado.getValueAt(fila, 5).toString());
                FormGestionarSalidaArticulo.tempProducto = tempProducto;
                 this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "no es un formulairo");
            }

        }
    }//GEN-LAST:event_listadoMousePressed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void rbtPrincipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtPrincipalMousePressed
        mostrar("principal");
        this.flag = "principal";
    }//GEN-LAST:event_rbtPrincipalMousePressed

    private void jRadioButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MousePressed
        mostrar("sotano");
        this.flag = "sotano";
    }//GEN-LAST:event_jRadioButton2MousePressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddnewProduct;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNumRegistro;
    private javax.swing.JTable listado;
    private javax.swing.JRadioButton rbtPrincipal;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
