/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package c1_precentacion;

import c2_aplicacion.GestionarAutorizanteServicio;
import c2_aplicacion.GestionarMovimientoServicio;
import c3_dominio.Configuracion;
import c3_dominio.LoginUser;
import c3_dominio.Movimiento;
import c3_dominio.Producto;
import c3_dominio.Autorizante;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Franz
 */
public class FormGestionarSalidaArticulo extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormGestionarUnidad
     */
    private String flag = "Guardar";
    private boolean rem = false;
    Movimiento movimiento;
    Producto producto;
    public static Producto tempProducto;
    public static Autorizante tempAutorizante;
    private GestionarMovimientoServicio gu;
    private List<Movimiento> movimientos;
    private List<Movimiento> templist = new ArrayList();
    private final LoginUser user = LoginUser.getInstancia();

    public FormGestionarSalidaArticulo(java.awt.Frame parent, boolean modal) {
        initComponents();
        lblPersonal.setText(user.getPersonal().getNombre() + " " + user.getPersonal().getApellidoPaterno() + " " + user.getPersonal().getApellidoMaterno());
        mostrar(templist);
        botones(false);
        cargarAutorizante();
        lblId.setVisible(false);
        lblIdArticulo.setVisible(false);
        lblindiceselect.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBuscarArticulo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblArticulo = new javax.swing.JLabel();
        testoplano = new javax.swing.JLabel();
        lblCodigoProducto = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jspCantidad = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        lblPersonal = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtUnidad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        btnAddArticulo = new javax.swing.JButton();
        btnRemoveArticulo = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtObservacion = new javax.swing.JTextArea();
        lblIdArticulo = new javax.swing.JLabel();
        lblindiceselect = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtSolicitante = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtAsunto = new javax.swing.JTextField();
        txtReferencia = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtSerie = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        txtCodUnt = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        txtCodSaneamiento = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lblProductoCantidad = new javax.swing.JLabel();
        lblSolicitante = new javax.swing.JLabel();
        cboAutorizante = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        txtNumSalida = new javax.swing.JFormattedTextField();
        txtNumExpediente = new javax.swing.JFormattedTextField();
        txtNumDocumento = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listado = new javax.swing.JTable();
        lblNumRegistro = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Administrador de Unidades");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Unidad"));

        jLabel1.setText("Producto :");

        lblId.setText("id");

        jLabel2.setText("Nº MEMO :");

        btnBuscarArticulo.setText("...");
        btnBuscarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarArticuloActionPerformed(evt);
            }
        });

        jLabel4.setText("Articulo : ");

        lblArticulo.setText("Producto");

        testoplano.setText("Cod :");

        lblCodigoProducto.setText("000");

        jLabel6.setText("Cantidad :");

        jLabel7.setText("Encargado : ");

        lblPersonal.setText("Personal");

        jLabel8.setText("Unidad :");

        jLabel9.setText("Marca :");

        jLabel10.setText("Color :");

        btnAddArticulo.setText("Agregar Producto");
        btnAddArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddArticuloActionPerformed(evt);
            }
        });

        btnRemoveArticulo.setText("Quitar Articulo");
        btnRemoveArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveArticuloActionPerformed(evt);
            }
        });

        jLabel12.setText("Observacion :");

        txtObservacion.setColumns(20);
        txtObservacion.setRows(5);
        jScrollPane3.setViewportView(txtObservacion);

        lblIdArticulo.setText("idarticulo");

        lblindiceselect.setText("indiceselect");

        jLabel3.setText("Nº Expediente :");

        jLabel5.setText("Nº Documento :");

        jLabel13.setText("Asunto : ");

        jLabel14.setText("Solicitante :");

        jLabel15.setText("Referencia :");

        jLabel21.setText("Nº serie : ");

        jLabel64.setText("Codigo Unt :");

        jLabel65.setText("Cod Saneamiento  :");

        jLabel11.setText("Cant :");

        lblProductoCantidad.setText("000");

        lblSolicitante.setText("Del :");

        jLabel16.setText("Modelo :");

        try {
            txtNumSalida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtNumExpediente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###############")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNumExpediente.setText("     ");

        try {
            txtNumDocumento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###############")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNumDocumento.setText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblId)
                        .addGap(165, 165, 165)
                        .addComponent(lblIdArticulo)
                        .addGap(18, 18, 18)
                        .addComponent(lblindiceselect)
                        .addGap(214, 214, 214))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel64)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel10)
                                        .addGap(21, 21, 21)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtCodUnt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 54, Short.MAX_VALUE))
                                    .addComponent(txtColor)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtUnidad)))
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6)
                        .addGap(3, 3, 3)
                        .addComponent(jspCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(2, 2, 2)
                                .addComponent(jScrollPane3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2)
                                    .addComponent(lblSolicitante))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtNumSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3)
                                                .addGap(5, 5, 5)
                                                .addComponent(txtNumExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtNumDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(cboAutorizante, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblPersonal)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel65)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCodSaneamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnBuscarArticulo)
                                        .addGap(6, 6, 6)
                                        .addComponent(testoplano)
                                        .addGap(3, 3, 3)
                                        .addComponent(lblCodigoProducto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblProductoCantidad)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblArticulo))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel21)
                                                .addGap(224, 224, 224))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnAddArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(58, 58, 58)))
                                        .addComponent(btnRemoveArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSolicitante)
                                    .addComponent(txtReferencia)
                                    .addComponent(txtAsunto))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(lblIdArticulo)
                    .addComponent(lblindiceselect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblPersonal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(txtNumSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSolicitante)
                    .addComponent(cboAutorizante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBuscarArticulo)
                    .addComponent(jLabel4)
                    .addComponent(lblArticulo)
                    .addComponent(testoplano)
                    .addComponent(lblCodigoProducto)
                    .addComponent(jLabel11)
                    .addComponent(lblProductoCantidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jspCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel64)
                    .addComponent(txtCodUnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel65)
                    .addComponent(txtCodSaneamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddArticulo)
                    .addComponent(btnRemoveArticulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listadoMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(listado);

        lblNumRegistro.setText("Nº Registros");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lblNumRegistro))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(494, 494, 494)
                        .addComponent(btnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNumRegistro))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiar() {
        lblId.setText("id");
        lblIdArticulo.setText("idarticulo");
        lblindiceselect.setText("indiceselect");
        txtNumSalida.setText("");
        txtNumExpediente.setText("");
        txtNumDocumento.setText("");
        txtSolicitante.setText("");
        lblSolicitante.setText("nombre");
        txtAsunto.setText("");
        txtReferencia.setText("");
        cboAutorizante.setSelectedIndex(0);
        limpiaradd();
        txtNumSalida.setText("");
        txtNumSalida.requestFocus();
        templist = new ArrayList();
        mostrar(templist);

    }

    private void limpiaradd() {
        lblCodigoProducto.setText("000");
        lblProductoCantidad.setText("000");
        lblArticulo.setText("Producto");
        txtObservacion.setText("");
        txtModelo.setText("");
        txtUnidad.setText("");
        txtMarca.setText("");
        txtColor.setText("");
        txtSerie.setText("");
        txtCodUnt.setText("");
        txtCodSaneamiento.setText("");
        jspCantidad.setValue(0);
        cboAutorizante.setSelectedIndex(0);
    }

    private void botones(boolean btn) {
        txtNumSalida.setEnabled(btn);
        txtNumSalida.setEnabled(btn);
        txtNumExpediente.setEnabled(btn);
        txtNumDocumento.setEnabled(btn);
        txtSolicitante.setEnabled(btn);
        txtAsunto.setEnabled(btn);
        txtReferencia.setEnabled(btn);
        txtObservacion.setEnabled(btn);
        txtUnidad.setEnabled(btn);
        txtMarca.setEnabled(btn);
        txtColor.setEnabled(btn);
        jspCantidad.setEnabled(btn);
        txtModelo.setEnabled(btn);
        txtSerie.setEnabled(btn);
        txtCodUnt.setEnabled(btn);
        txtCodSaneamiento.setEnabled(btn);
        cboAutorizante.setEnabled(btn);
        btnCancelar.setEnabled(btn);
        btnNuevo.setEnabled(!btn);
        btnBuscarArticulo.setEnabled(btn);
        btnAddArticulo.setEnabled(btn);
        btnRemoveArticulo.setEnabled(btn);
        btnGuardar.setEnabled(btn);

    }

    private void cargarAutorizante() {
        GestionarAutorizanteServicio guc = new GestionarAutorizanteServicio();
        try {
            for (Autorizante aut : guc.listar()) {
                cboAutorizante.addItem(aut.getDescripcion());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    private void mostrar(List<Movimiento> movimientos) {
        try {
            gu = new GestionarMovimientoServicio();
            gu.llenarLista(listado, movimientos);
            lblNumRegistro.setText("Nº Registros : " + String.valueOf(listado.getRowCount()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (!txtNumSalida.getText().equals("")) {
            if (templist.size() >= 1) {
                try {
                    gu = new GestionarMovimientoServicio();
                    if (flag.equals("Guardar")) {
                        for (Movimiento dts : templist) {
                            gu.removeCantidad(dts);
                            if (gu.insertarSalida(dts)) {
                                JOptionPane.showMessageDialog(null, "Guardado correctamente");
                            } else {
                                JOptionPane.showMessageDialog(null, "No se pudo guardar");
                            }
                        }
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Debe Seleccionar almenos un articulo", "Aviso", 0);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe ingresar un numero de documento", "Aviso", 0);
            txtNumSalida.requestFocus();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiar();
        botones(false);
        btnGuardar.setText("Guardar");
        flag = "Guardar";
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiar();
        botones(true);
        btnGuardar.setText("Guardar");
        flag = "Guardar";
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void listadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadoMouseClicked
        int fila = listado.rowAtPoint(evt.getPoint());
        lblIdArticulo.setText(listado.getValueAt(fila, 0).toString());
        jspCantidad.setValue(Integer.parseInt(listado.getValueAt(fila, 1).toString()));
        txtUnidad.setText(listado.getValueAt(fila, 2).toString());
        lblCodigoProducto.setText(listado.getValueAt(fila, 3).toString());
        lblArticulo.setText(listado.getValueAt(fila, 4).toString());
        txtReferencia.setText(listado.getValueAt(fila, 5).toString());
        txtObservacion.setText(listado.getValueAt(fila, 6).toString());
        txtMarca.setText(listado.getValueAt(fila, 7).toString());
        txtColor.setText(listado.getValueAt(fila, 8).toString());
        lblindiceselect.setText(String.valueOf(listado.getSelectedRow()));
        this.rem = true;
    }//GEN-LAST:event_listadoMouseClicked

    private void btnAddArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddArticuloActionPerformed
        movimiento = new Movimiento();
        try {
            if (!lblCodigoProducto.getText().equals("000")) {
                if (tempProducto.getCantidad() > 0) {
                    if (Integer.parseInt(jspCantidad.getValue().toString()) > 0) {
                        if (Integer.parseInt(jspCantidad.getValue().toString()) <= tempProducto.getCantidad()) {
                            movimiento.setOperacion("salida");
                            Calendar calendar = Calendar.getInstance();
                            Timestamp fecha = new Timestamp(calendar.getTime().getTime());
                            movimiento.setFechaRegistro(fecha);
                            Configuracion conf = new Configuracion();
                            movimiento.setNumSalida(conf.generarCodigo(txtNumSalida.getText().toUpperCase().trim()));
                            movimiento.setNumExpediente(txtNumExpediente.getText().trim());
                            movimiento.setNumDocumento(txtNumDocumento.getText().trim());
                            movimiento.setAsunto(txtAsunto.getText().trim());
                            movimiento.setSolicitante(txtSolicitante.getText().trim());
                            movimiento.setReferencia(txtReferencia.getText().trim());
                            movimiento.setCantidad(Integer.parseInt(jspCantidad.getValue().toString()));
                            movimiento.setModelo(txtModelo.getText().trim());
                            movimiento.setColor(txtColor.getText().trim());
                            movimiento.setNumSerie(txtSerie.getText().trim());
                            movimiento.setCodigoUnt(txtCodUnt.getText().trim());
                            movimiento.setCodigoSaneamiento(txtCodSaneamiento.getText().trim());
                            movimiento.setObservacion(txtObservacion.getText().trim());
                            GestionarAutorizanteServicio gas = new GestionarAutorizanteServicio();
                            movimiento.setAutorizante(gas.obtenerId(gas.listar(), cboAutorizante.getSelectedItem().toString()));
                            movimiento.setPersonal(user.getPersonal());
                            movimiento.setProducto(tempProducto);
                            templist.add(movimiento);
                            mostrar(templist);
                            limpiaradd();
                        } else {
                            JOptionPane.showMessageDialog(null, "La cantidad supera al stock actual del producto", "aviso", 2);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "la cantidad minima debe ser 1", "aviso", 2);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El producto no cuenta con stock", "aviso", 2);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Debe Seleccionar un articulo almenos", "aviso", 2);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnAddArticuloActionPerformed

    private void btnBuscarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarArticuloActionPerformed
        FormProductoListado form = new FormProductoListado(null,true,"salida");
        FormPrincipal.escritorio.add(form);
        form.toFront();
        tempProducto = new Producto();
        form.tempProducto = tempProducto;
        form.setVisible(true);
    }//GEN-LAST:event_btnBuscarArticuloActionPerformed

    private void listadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_listadoMousePressed

    private void btnRemoveArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveArticuloActionPerformed
        if (this.rem) {
            templist.remove(Integer.parseInt(lblindiceselect.getText()));
            mostrar(templist);
            limpiaradd();
            this.rem = false;
        } else {
            JOptionPane.showMessageDialog(null, "Debe Seleccionar un articulo de la lista", "aviso", 1);
        }
    }//GEN-LAST:event_btnRemoveArticuloActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddArticulo;
    private javax.swing.JButton btnBuscarArticulo;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRemoveArticulo;
    private javax.swing.JComboBox cboAutorizante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jspCantidad;
    public static javax.swing.JLabel lblArticulo;
    public static javax.swing.JLabel lblCodigoProducto;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIdArticulo;
    private javax.swing.JLabel lblNumRegistro;
    private javax.swing.JLabel lblPersonal;
    public static javax.swing.JLabel lblProductoCantidad;
    public static javax.swing.JLabel lblSolicitante;
    private javax.swing.JLabel lblindiceselect;
    private javax.swing.JTable listado;
    private javax.swing.JLabel testoplano;
    private javax.swing.JTextField txtAsunto;
    private javax.swing.JTextField txtCodSaneamiento;
    private javax.swing.JTextField txtCodUnt;
    private javax.swing.JTextField txtColor;
    public static javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JFormattedTextField txtNumDocumento;
    private javax.swing.JFormattedTextField txtNumExpediente;
    private javax.swing.JFormattedTextField txtNumSalida;
    private javax.swing.JTextArea txtObservacion;
    private javax.swing.JTextField txtReferencia;
    private javax.swing.JTextField txtSerie;
    private javax.swing.JTextField txtSolicitante;
    public static javax.swing.JTextField txtUnidad;
    // End of variables declaration//GEN-END:variables
}
