/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package c1_precentacion;

import c2_aplicacion.GestionarMovimientoServicio;
import c3_dominio.Area;
import c3_dominio.Configuracion;
import c3_dominio.LoginUser;
import c3_dominio.Movimiento;
import c3_dominio.Producto;
import c3_dominio.Solicitante;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Franz
 */
public class FormGestionarSalidaArticulo extends javax.swing.JDialog {

    /**
     * Creates new form FormGestionarUnidad
     */
    private String flag = "Guardar";
    Movimiento movimiento;
    Producto producto;
    public static Producto tempProducto;
    public static Area tempArea;
    public static Solicitante tempSolicitante;
    private GestionarMovimientoServicio gu;
    private List<Movimiento> movimientos;
    private List<Movimiento> templist = new ArrayList();
    private final LoginUser user = LoginUser.getInstancia();

    public FormGestionarSalidaArticulo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lblPersonal.setText(user.getPersonal().getNombre() + " " + user.getPersonal().getApellidoPaterno() + " " + user.getPersonal().getApellidoMaterno());
        mostrar(templist);
        botones(false);
        lblId.setVisible(false);
        lblIdArticulo.setVisible(false);
        lblindiceselect.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumSalida = new javax.swing.JTextField();
        btnBuscarArticulo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblArticulo = new javax.swing.JLabel();
        testoplano = new javax.swing.JLabel();
        lblCodigoProducto = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jspCantidad = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        lblPersonal = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtUnidad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtMedida = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        btnAddArticulo = new javax.swing.JButton();
        btnRemoveArticulo = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtObservacion = new javax.swing.JTextArea();
        lblIdArticulo = new javax.swing.JLabel();
        lblindiceselect = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNumExpediente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNumDocumento = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtAutoriza = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        txtAsunto = new javax.swing.JTextField();
        txtReferencia = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        lblSolicitante = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        btnSolicitante = new javax.swing.JButton();
        btnArea = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txtSerie = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        txtCodUnt = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        txtCodSaneamiento = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lblProductoCantidad = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listado = new javax.swing.JTable();
        lblNumRegistro = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrador de Unidades");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Unidad"));

        jLabel1.setText("Producto :");

        lblId.setText("id");

        jLabel2.setText("Nº Salida :");

        btnBuscarArticulo.setText("...");
        btnBuscarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarArticuloActionPerformed(evt);
            }
        });

        jLabel4.setText("Articulo : ");

        lblArticulo.setText("Producto");

        testoplano.setText("Cod :");

        lblCodigoProducto.setText("000");

        jLabel6.setText("Cantidad :");

        jLabel7.setText("Encargado : ");

        lblPersonal.setText("Personal");

        jLabel8.setText("Unidad :");

        jLabel9.setText("Medida :");

        jLabel10.setText("Color :");

        btnAddArticulo.setText("Agregar Producto");
        btnAddArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddArticuloActionPerformed(evt);
            }
        });

        btnRemoveArticulo.setText("Quitar Articulo");
        btnRemoveArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveArticuloActionPerformed(evt);
            }
        });

        jLabel12.setText("Observacion :");

        txtObservacion.setColumns(20);
        txtObservacion.setRows(5);
        jScrollPane3.setViewportView(txtObservacion);

        lblIdArticulo.setText("idarticulo");

        lblindiceselect.setText("indiceselect");

        jLabel3.setText("Nº Expediente :");

        jLabel5.setText("Nº Documento :");

        jLabel13.setText("Asunto : ");

        jLabel14.setText("Autoriza : ");

        jLabel15.setText("Referencia :");

        jLabel16.setText("Modelo :");

        lblSolicitante.setText("nombre");

        lblArea.setText("area");

        btnSolicitante.setText("Solicitante");
        btnSolicitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitanteActionPerformed(evt);
            }
        });

        btnArea.setText("Area");
        btnArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaActionPerformed(evt);
            }
        });

        jLabel21.setText("Nº serie : ");

        jLabel64.setText("Codigo Unt :");

        jLabel65.setText("Cod Saneamiento  :");

        jLabel11.setText("Cant :");

        lblProductoCantidad.setText("000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel65)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodSaneamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addComponent(jLabel13))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtReferencia)
                                .addComponent(txtAsunto)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(2, 2, 2)
                            .addComponent(jScrollPane3))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnBuscarArticulo)
                            .addGap(6, 6, 6)
                            .addComponent(testoplano)
                            .addGap(3, 3, 3)
                            .addComponent(lblCodigoProducto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblProductoCantidad)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblArticulo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtUnidad))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(21, 21, 21)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtColor)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jspCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(61, 61, 61)
                                                    .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jLabel21))
                                            .addGap(24, 24, 24)
                                            .addComponent(jLabel64)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(btnAddArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(58, 58, 58)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnRemoveArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCodUnt, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel2)
                                        .addComponent(btnSolicitante))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblSolicitante)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtNumSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtNumExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtNumDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lblPersonal)
                                        .addComponent(txtAutoriza, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblId)
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(lblIdArticulo)
                                .addGap(18, 18, 18)
                                .addComponent(lblindiceselect)
                                .addGap(214, 214, 214))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(287, 287, 287)
                                .addComponent(btnArea)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblArea)
                                .addGap(49, 49, 49)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(lblIdArticulo)
                    .addComponent(lblindiceselect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblPersonal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtNumExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtNumDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtAutoriza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSolicitante)
                    .addComponent(lblSolicitante)
                    .addComponent(btnArea)
                    .addComponent(lblArea))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBuscarArticulo)
                    .addComponent(jLabel4)
                    .addComponent(lblArticulo)
                    .addComponent(testoplano)
                    .addComponent(lblCodigoProducto)
                    .addComponent(jLabel11)
                    .addComponent(lblProductoCantidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jspCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel64)
                    .addComponent(txtCodUnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel65)
                    .addComponent(txtCodSaneamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddArticulo)
                    .addComponent(btnRemoveArticulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listadoMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(listado);

        lblNumRegistro.setText("Nº Registros");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(btnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lblNumRegistro))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNumRegistro))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar)
                    .addComponent(btnEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiar() {
        lblId.setText("id");
        lblIdArticulo.setText("idarticulo");
        lblindiceselect.setText("indiceselect");
        txtNumSalida.setText("");
        txtNumExpediente.setText("");
        txtNumDocumento.setText("");
        txtAutoriza.setText("");
        lblSolicitante.setText("nombre");
        lblArea.setText("area");
        txtAsunto.setText("");
        txtReferencia.setText("");
        limpiaradd();
        txtNumSalida.setText("");
        txtNumSalida.requestFocus();
        templist = new ArrayList();
        mostrar(templist);

    }

    private void limpiaradd() {
        lblCodigoProducto.setText("000");
        lblArticulo.setText("Producto");
        txtObservacion.setText("");
        txtModelo.setText("");
        txtUnidad.setText("");
        txtMedida.setText("");
        txtColor.setText("");
        txtSerie.setText("");
        txtCodUnt.setText("");
        txtCodSaneamiento.setText("");
        jspCantidad.setValue(0);
    }

    private void botones(boolean btn) {
        txtNumSalida.setEnabled(btn);
        txtNumSalida.setEnabled(btn);
        txtNumExpediente.setEnabled(btn);
        txtNumDocumento.setEnabled(btn);
        txtAutoriza.setEnabled(btn);
        txtAsunto.setEnabled(btn);
        txtReferencia.setEnabled(btn);
        txtObservacion.setEnabled(btn);
        txtUnidad.setEnabled(btn);
        txtMedida.setEnabled(btn);
        txtColor.setEnabled(btn);
        jspCantidad.setEnabled(btn);
        txtModelo.setEnabled(btn);
        txtSerie.setEnabled(btn);
        txtCodUnt.setEnabled(btn);
        txtCodSaneamiento.setEnabled(btn);
        btnCancelar.setEnabled(btn);
        btnNuevo.setEnabled(!btn);
        btnEliminar.setEnabled(btn);
        btnBuscarArticulo.setEnabled(btn);
        btnAddArticulo.setEnabled(btn);
        btnRemoveArticulo.setEnabled(btn);
        btnGuardar.setEnabled(btn);
        btnSolicitante.setEnabled(btn);
        btnArea.setEnabled(btn);

    }

    private void mostrar(List<Movimiento> movimientos) {
        try {
            gu = new GestionarMovimientoServicio();
            gu.llenarLista(listado, movimientos);
            lblNumRegistro.setText("Nº Registros : " + String.valueOf(listado.getRowCount()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

//    private boolean buscarMarcaList(String nombre) {
//        boolean flag = false;
//        gu = new GestionarMovimientoServicio();
//        try {
//            movimientos = gu.listar();
//            flag = (gu.buscarMovimientoList(movimientos, nombre)) ? true : false;
//
//        } catch (Exception e) {
//        }
//        return flag;
//    }
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // if (!txtNombre.getText().equals("")) {
        try {
            gu = new GestionarMovimientoServicio();
            if (flag.equals("Guardar")) {
                // if (!buscarMarcaList(txtNombre.getText().toLowerCase().trim())) {
                for (Movimiento dts : templist) {
                    gu.removeCantidad(dts);
                    if (gu.insertarSalida(dts)) {
                        JOptionPane.showMessageDialog(null, "Guardado correctamente");

                    } else {
                        JOptionPane.showMessageDialog(null, "No se pudo guardar");

                    }
                }
//                    } else {
//                        JOptionPane.showMessageDialog(this, "la unidad ya existe");
//                        txtNombre.requestFocus();
//                    }
            } else {
                movimiento.setId(Integer.parseInt(lblId.getText()));
                if (gu.editar(movimiento)) {
                    JOptionPane.showMessageDialog(null, "Se Actualizo correctamente");
                    //mostrar();
                    limpiar();
                    botones(false);
                } else {
                    JOptionPane.showMessageDialog(null, "no se pudo actualizar");
                    //mostrar();
                    limpiar();
                    botones(false);
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
//        } else {
//            JOptionPane.showMessageDialog(this, "Debe llenar el nombre", "Aviso", 0);
////            txtNombre.requestFocus();
//        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        //mostrar();
        limpiar();
        botones(false);
        btnGuardar.setText("Guardar");
        flag = "Guardar";
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        //mostrar();
        limpiar();
        botones(true);
        btnGuardar.setText("Guardar");
        flag = "Guardar";
        btnEliminar.setEnabled(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void listadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadoMouseClicked
        int fila = listado.rowAtPoint(evt.getPoint());
        lblIdArticulo.setText(listado.getValueAt(fila, 0).toString());
        jspCantidad.setValue(Integer.parseInt(listado.getValueAt(fila, 1).toString()));
        txtUnidad.setText(listado.getValueAt(fila, 2).toString());
        lblCodigoProducto.setText(listado.getValueAt(fila, 3).toString());
        lblArticulo.setText(listado.getValueAt(fila, 4).toString());
        txtReferencia.setText(listado.getValueAt(fila, 5).toString());
        txtObservacion.setText(listado.getValueAt(fila, 6).toString());
        txtMedida.setText(listado.getValueAt(fila, 7).toString());
        txtColor.setText(listado.getValueAt(fila, 8).toString());
        lblindiceselect.setText(String.valueOf(listado.getSelectedRow()));

    }//GEN-LAST:event_listadoMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (!lblId.getText().equals("id")) {
            int res = JOptionPane.showConfirmDialog(this, "¿Esta Seguro De Eliminar?", "Eliminar", 0, 3);
            if (res == 0) {
                try {
                    gu = new GestionarMovimientoServicio();
                    movimiento = new Movimiento();
                    movimiento.setId(Integer.parseInt(lblId.getText()));
                    if (gu.eliminar(movimiento)) {
                        JOptionPane.showMessageDialog(this, "Eliminado correctamente");
                        // mostrar();
                        limpiar();
                        botones(false);
                        btnGuardar.setText("Guardar");
                        flag = "Guardar";
                    } else {
                        JOptionPane.showMessageDialog(this, "No se pudo eliminar", "Aviso", 2);
                        //mostrar();
                        limpiar();
                        botones(false);
                        btnGuardar.setText("Guardar");
                        flag = "Guardar";
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e);
                }
            } else {
                //mostrar();
                limpiar();
                botones(false);
                btnGuardar.setText("Guardar");
                flag = "Guardar";
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe de selecionar una Unidad para eliminar", "Aviso", 2);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAddArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddArticuloActionPerformed
        movimiento = new Movimiento();
        if (tempProducto.getCantidad() > 0) {
            if (Integer.parseInt(jspCantidad.getValue().toString()) > 0) {
                if (Integer.parseInt(jspCantidad.getValue().toString()) <= tempProducto.getCantidad()) {
                    movimiento.setOperacion("salida");
                    Calendar calendar = Calendar.getInstance();
                    Timestamp fecha = new Timestamp(calendar.getTime().getTime());
                    movimiento.setFechaRegistro(fecha);
                    Configuracion conf = new Configuracion();
                    movimiento.setNumSalida(conf.generarCodigo(txtNumSalida.getText().toUpperCase().trim()));
                    movimiento.setNumExpediente(txtNumExpediente.getText().trim());
                    movimiento.setNumDocumento(txtNumDocumento.getText().trim());
                    movimiento.setAsunto(txtAsunto.getText().trim());
                    movimiento.setAutoriza(txtAutoriza.getText().trim());
                    movimiento.setReferencia(txtReferencia.getText().trim());
                    movimiento.setCantidad(Integer.parseInt(jspCantidad.getValue().toString()));
                    movimiento.setModelo(txtModelo.getText().trim());
                    movimiento.setUnidad(txtUnidad.getText().trim());
                    movimiento.setMedida(txtMedida.getText().trim());
                    movimiento.setColor(txtColor.getText().trim());
                    movimiento.setNumSerie(txtSerie.getText().trim());
                    movimiento.setCodigoUnt(txtCodUnt.getText().trim());
                    movimiento.setCodigoSaneamiento(txtCodSaneamiento.getText().trim());
                    movimiento.setObservacion(txtObservacion.getText().trim());
                    movimiento.setArea(tempArea);
                    movimiento.setSolicitamte(tempSolicitante);
                    movimiento.setPersonal(user.getPersonal());
                    movimiento.setProducto(tempProducto);
                    templist.add(movimiento);
                    mostrar(templist);
                    limpiaradd();
                } else {
                    JOptionPane.showMessageDialog(null, "La cantidad supera al stock actual del producto", "aviso", 2);
                }
            } else {
                JOptionPane.showMessageDialog(null, "la cantidad minima debe ser 1", "aviso", 2);
            }
        } else {
            JOptionPane.showMessageDialog(null, "El producto no cuenta con stock", "aviso", 2);
        }
    }//GEN-LAST:event_btnAddArticuloActionPerformed

    private void btnBuscarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarArticuloActionPerformed
        FormProductoListado form = new FormProductoListado(null, false, "salida");
        form.toFront();
        tempProducto = new Producto();
        form.tempProducto = tempProducto;
        form.setVisible(true);
    }//GEN-LAST:event_btnBuscarArticuloActionPerformed

    private void listadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_listadoMousePressed

    private void btnRemoveArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveArticuloActionPerformed
        templist.remove(Integer.parseInt(lblindiceselect.getText()));
        mostrar(templist);
        limpiaradd();

    }//GEN-LAST:event_btnRemoveArticuloActionPerformed

    private void btnSolicitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitanteActionPerformed
        FormGestionarSolicitante form = new FormGestionarSolicitante(null, false);
        form.toFront();
        tempSolicitante = new Solicitante();
        form.tempSolicitante = tempSolicitante;
        form.setVisible(true);
    }//GEN-LAST:event_btnSolicitanteActionPerformed

    private void btnAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaActionPerformed
        FormGestionarArea form = new FormGestionarArea(null, false);
        form.toFront();
        tempArea = new Area();
        //  form.tempArea = tempArea;
        form.setVisible(true);
    }//GEN-LAST:event_btnAreaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddArticulo;
    private javax.swing.JButton btnArea;
    private javax.swing.JButton btnBuscarArticulo;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRemoveArticulo;
    private javax.swing.JButton btnSolicitante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jspCantidad;
    public static javax.swing.JLabel lblArea;
    public static javax.swing.JLabel lblArticulo;
    public static javax.swing.JLabel lblCodigoProducto;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIdArticulo;
    private javax.swing.JLabel lblNumRegistro;
    private javax.swing.JLabel lblPersonal;
    public static javax.swing.JLabel lblProductoCantidad;
    public static javax.swing.JLabel lblSolicitante;
    private javax.swing.JLabel lblindiceselect;
    private javax.swing.JTable listado;
    private javax.swing.JLabel testoplano;
    private javax.swing.JTextField txtAsunto;
    private javax.swing.JTextField txtAutoriza;
    private javax.swing.JTextField txtCodSaneamiento;
    private javax.swing.JTextField txtCodUnt;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtMedida;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNumDocumento;
    private javax.swing.JTextField txtNumExpediente;
    private javax.swing.JTextField txtNumSalida;
    private javax.swing.JTextArea txtObservacion;
    private javax.swing.JTextField txtReferencia;
    private javax.swing.JTextField txtSerie;
    private javax.swing.JTextField txtUnidad;
    // End of variables declaration//GEN-END:variables
}
