/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package c1_precentacion;

import c2_aplicacion.GestionarAlmacenServicio;
import c2_aplicacion.GestionarCategoriaServicio;
import c2_aplicacion.GestionarMarcaServicio;
import c2_aplicacion.GestionarProductoServicio;
import c2_aplicacion.GestionarTipoProductoServicio;
import c2_aplicacion.GestionarUnidadServicio;
import c3_dominio.Almacen;
import c3_dominio.Categoria;
import c3_dominio.Marca;
import c3_dominio.Producto; 
import c3_dominio.TipoProducto;
import c3_dominio.Unidad;
import java.sql.Timestamp;   
import java.util.List;
import javax.swing.JOptionPane; 
import java.util.Calendar;

/**
 *
 * @author Franz
 */
public class FormGestionarProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormGestionarUnidad
     */
    private String flag = "Guardar";
    Producto producto;
    public Producto tempProducto;
    private GestionarProductoServicio gu;
    private List<Producto> productos;

    public FormGestionarProducto(java.awt.Frame parent, boolean modal) { 
        initComponents(); 
        carga();
        botones(false);
        lblId.setVisible(false);
        tempProducto = new Producto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cboCategoria = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        cboTipoProducto = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        cboMarca = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        cboAlmacen = new javax.swing.JComboBox();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        cboUnidad = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNombre = new javax.swing.JTextArea();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Administrador de Unidades");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Producto"));

        jLabel1.setText("Articulo :");

        lblId.setText("id");

        jLabel2.setText("Codigo : ");

        jLabel5.setText("Fecha :");

        jLabel6.setText("Unidad : ");

        jLabel8.setText("Categoria : ");

        jLabel9.setText("Tipo  :");

        jLabel10.setText("Marca :");

        jLabel11.setText("Almacen :");

        jdcFecha.setDateFormatString("yyyy-MM-dd hh:mm:ss");

        txtNombre.setColumns(20);
        txtNombre.setRows(5);
        jScrollPane1.setViewportView(txtNombre);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(26, 26, 26)
                        .addComponent(cboUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(13, 13, 13)
                        .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblId)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(20, 20, 20)
                            .addComponent(cboAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel5))
                            .addGap(26, 26, 26)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(cboUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(cboTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cboAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(403, 403, 403))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar)
                    .addComponent(btnEliminar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiar() {
        lblId.setText("id");
        txtCodigo.setText("");
        txtNombre.setText(""); 
        cboCategoria.setSelectedIndex(0);
        cboTipoProducto.setSelectedIndex(0);
        cboMarca.setSelectedIndex(0);
        cboAlmacen.setSelectedIndex(0);
        cboUnidad.setSelectedIndex(0);
        txtCodigo.requestFocus(); 
        jdcFecha.setCalendar(null);
    }

    private void botones(boolean btn) {
        txtCodigo.setEnabled(btn);
        txtNombre.setEnabled(btn);
        cboUnidad.setEnabled(btn);
        cboCategoria.setEnabled(btn);
        cboTipoProducto.setEnabled(btn);
        cboMarca.setEnabled(btn);
        cboAlmacen.setEnabled(btn);
        btnGuardar.setEnabled(btn);
        btnCancelar.setEnabled(btn);
        btnNuevo.setEnabled(!btn);
        btnEliminar.setEnabled(btn);
        jdcFecha.setEnabled(btn);
    }

    private void carga() {
        cargarCategoria();
        cargarTipo();
        cargarMarca();
        cargarAlmacen();
        cargarUnidad();
    }

    private void cargarCategoria() {
        GestionarCategoriaServicio guc = new GestionarCategoriaServicio();
        try {
            for (Categoria cat : guc.listar()) {
                cboCategoria.addItem(cat.getDescripcion());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    private void cargarTipo() {
        GestionarTipoProductoServicio guc = new GestionarTipoProductoServicio();
        try {
            for (TipoProducto cat : guc.listar()) {
                cboTipoProducto.addItem(cat.getDescripcion());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    private void cargarMarca() {
        GestionarMarcaServicio guc = new GestionarMarcaServicio();
        try {
            for (Marca cat : guc.listar()) {
                cboMarca.addItem(cat.getDescripcion());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    private void cargarAlmacen() {
        GestionarAlmacenServicio guc = new GestionarAlmacenServicio();
        try {
            for (Almacen cat : guc.listar()) {
                cboAlmacen.addItem(cat.getDescripcion());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    
    private void cargarUnidad() {
        GestionarUnidadServicio gus = new GestionarUnidadServicio();
        try {
            for (Unidad cat : gus.listar()) {
                cboUnidad.addItem(cat.getDescripcion());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    

    private boolean buscarProdutoList(String nombre) {
        boolean flag = false;
        gu = new GestionarProductoServicio();
        try {
            productos = gu.listar();
            flag = (gu.buscarProductoList(productos, nombre)) ? true : false;

        } catch (Exception e) {
        }
        return flag;
    }
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (!txtNombre.getText().equals("")) {
            try {
                producto = new Producto();
                gu = new GestionarProductoServicio();
                producto.setCodigo(txtCodigo.getText().toUpperCase().trim());
                producto.setArticulo(txtNombre.getText().toLowerCase().trim()); 
                Calendar calendar = Calendar.getInstance();
                calendar = jdcFecha.getCalendar();
                Timestamp fecha = new Timestamp(calendar.getTime().getTime());
                producto.setFechaRegistro(fecha);  
                GestionarCategoriaServicio gcs = new GestionarCategoriaServicio();
                producto.setCategoria(gcs.obtenerId(gcs.listar(), cboCategoria.getSelectedItem().toString()));
                GestionarTipoProductoServicio tp = new GestionarTipoProductoServicio();
                producto.setTipoProducto(tp.obtenerId(tp.listar(), cboTipoProducto.getSelectedItem().toString()));
                GestionarMarcaServicio gms = new GestionarMarcaServicio();
                producto.setMarca(gms.obtenerId(gms.listar(), cboMarca.getSelectedItem().toString()));
                GestionarAlmacenServicio gas = new GestionarAlmacenServicio();
                producto.setAlmacen(gas.obtenerId(gas.listar(), cboAlmacen.getSelectedItem().toString()));
                GestionarUnidadServicio gus = new GestionarUnidadServicio();
                producto.setUnidad(gus.obtenerId(gus.listar(),cboUnidad.getSelectedItem().toString()));  
                if (flag.equals("Guardar")) { 
                    if (!buscarProdutoList(txtNombre.getText().toLowerCase().trim())) {
                        if (gu.insertar(producto)) {
                            JOptionPane.showMessageDialog(null, "Guardado correctamente"); 
                            limpiar();
                            botones(false);
                        } else {
                            JOptionPane.showMessageDialog(null, "NO se pudo guardar"); 
                            limpiar();
                            botones(false);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "la unidad ya existe");
                        txtNombre.requestFocus();
                    }
                } else {
                    producto.setId(Integer.parseInt(lblId.getText()));
                    if (gu.editar(producto)) {
                        JOptionPane.showMessageDialog(null, "Se Actualizo correctamente"); 
                        limpiar();
                        botones(false);
                    } else {
                        JOptionPane.showMessageDialog(null, "no se pudo actualizar"); 
                        limpiar();
                        botones(false);
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe llenar el nombre", "Aviso", 0);
            txtNombre.requestFocus();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiar();
        botones(false);
        btnGuardar.setText("Guardar");
        flag = "Guardar";
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiar();
        botones(true);
        btnEliminar.setEnabled(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (!lblId.getText().equals("id")) {
            int res = JOptionPane.showConfirmDialog(this, "¿Esta Seguro De Eliminar?", "Eliminar", 0, 3);
            if (res == 0) {
                try {
                    gu = new GestionarProductoServicio();
                    producto = new Producto();
                    producto.setId(Integer.parseInt(lblId.getText()));
                    if (gu.eliminar(producto)) {
                        JOptionPane.showMessageDialog(this, "Eliminado correctamente"); 
                        limpiar();
                        botones(false);
                        btnGuardar.setText("Guardar");
                        flag = "Guardar";
                    } else {
                        JOptionPane.showMessageDialog(this, "No se pudo eliminar", "Aviso", 2); 
                        limpiar();
                        botones(false);
                        btnGuardar.setText("Guardar");
                        flag = "Guardar";
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e);
                }
            } else { 
                limpiar();
                botones(false);
                btnGuardar.setText("Guardar");
                flag = "Guardar";
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe de selecionar una Unidad para eliminar", "Aviso", 2);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed
   
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox cboAlmacen;
    private javax.swing.JComboBox cboCategoria;
    private javax.swing.JComboBox cboMarca;
    private javax.swing.JComboBox cboTipoProducto;
    private javax.swing.JComboBox cboUnidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcFecha;
    private javax.swing.JLabel lblId;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtNombre;
    // End of variables declaration//GEN-END:variables
}
