/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package c1_precentacion;

/**
 *
 * @author Franz
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        miArchivo = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        miArea = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        miProductos = new javax.swing.JMenuItem();
        miProductos4 = new javax.swing.JMenuItem();
        miProductos1 = new javax.swing.JMenuItem();
        miProductos2 = new javax.swing.JMenuItem();
        miProductos3 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        smiPersonal = new javax.swing.JMenuItem();
        smiCargos = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(0, 255, 255));

        miArchivo.setMnemonic('f');
        miArchivo.setText("Archivo");
        miArchivo.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N

        exitMenuItem.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        miArchivo.add(exitMenuItem);

        menuBar.add(miArchivo);

        jMenu1.setText("Movimiento");
        jMenu1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jMenuItem1.setText("Ingreso de Producto");
        jMenu1.add(jMenuItem1);

        miArea.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        miArea.setText("Salida de Producto");
        miArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAreaActionPerformed(evt);
            }
        });
        jMenu1.add(miArea);

        menuBar.add(jMenu1);

        jMenu2.setText("Mantenimiento");
        jMenu2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N

        jMenu6.setText("Productos");
        jMenu6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N

        miProductos.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        miProductos.setText("Producto");
        jMenu6.add(miProductos);

        miProductos4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        miProductos4.setText("Almacen");
        jMenu6.add(miProductos4);

        miProductos1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        miProductos1.setText("Categoria");
        jMenu6.add(miProductos1);

        miProductos2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        miProductos2.setText("Marca");
        jMenu6.add(miProductos2);

        miProductos3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        miProductos3.setText("Unidad");
        jMenu6.add(miProductos3);

        jMenu2.add(jMenu6);

        jMenu5.setText("Personal");
        jMenu5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N

        smiPersonal.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        smiPersonal.setText("Personal");
        smiPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smiPersonalActionPerformed(evt);
            }
        });
        jMenu5.add(smiPersonal);

        smiCargos.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        smiCargos.setText("Cargos");
        smiCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smiCargosActionPerformed(evt);
            }
        });
        jMenu5.add(smiCargos);

        jMenu2.add(jMenu5);

        jMenu7.setText("Solicitantes");
        jMenu7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jMenuItem2.setText("Solicitante");
        jMenu7.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jMenuItem3.setText("Area");
        jMenu7.add(jMenuItem3);

        jMenu2.add(jMenu7);

        menuBar.add(jMenu2);

        jMenu3.setText("Consultas");
        jMenu3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        menuBar.add(jMenu3);

        jMenu4.setText("Reportes");
        jMenu4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        menuBar.add(jMenu4);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void miAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAreaActionPerformed
       FormGestionarArea area = new FormGestionarArea(this,true); 
       area.show();
    }//GEN-LAST:event_miAreaActionPerformed

    private void smiPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smiPersonalActionPerformed
        FormGestionarPersonal form = new FormGestionarPersonal(this, true);
        form.setVisible(true);
    }//GEN-LAST:event_smiPersonalActionPerformed

    private void smiCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smiCargosActionPerformed
        FormGestionarTipoPersonal form = new FormGestionarTipoPersonal(this,true);
        form.setVisible(true);
    }//GEN-LAST:event_smiCargosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu miArchivo;
    private javax.swing.JMenuItem miArea;
    private javax.swing.JMenuItem miProductos;
    private javax.swing.JMenuItem miProductos1;
    private javax.swing.JMenuItem miProductos2;
    private javax.swing.JMenuItem miProductos3;
    private javax.swing.JMenuItem miProductos4;
    private javax.swing.JMenuItem smiCargos;
    private javax.swing.JMenuItem smiPersonal;
    // End of variables declaration//GEN-END:variables

}
