/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package c1_precentacion;

import c3_dominio.Personal;
import c3_dominio.LoginUser;
import javax.swing.JOptionPane;

/**
 *
 * @author Franz
 */
public class FormMenu extends javax.swing.JFrame { 
    /**
     * Creates new form FormMenu
     */
    public FormMenu() {  
        setExtendedState(MAXIMIZED_BOTH);
        initComponents();   
        LoginUser user = LoginUser.getInstancia();
        lblNombre.setText(user.getPersonal().getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miSalir = new javax.swing.JMenuItem();
        miTipoPersonal = new javax.swing.JMenu();
        miUnidad = new javax.swing.JMenuItem();
        miCategoria = new javax.swing.JMenuItem();
        miMarca = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        miArea = new javax.swing.JMenuItem();
        miAlamcen = new javax.swing.JMenuItem();
        miPersonal = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNombre.setText("jLabel1");

        jMenu1.setText("File");

        miSalir.setText("Salir");
        miSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalirActionPerformed(evt);
            }
        });
        jMenu1.add(miSalir);

        jMenuBar1.add(jMenu1);

        miTipoPersonal.setText("Edit");

        miUnidad.setText("Unidades");
        miUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUnidadActionPerformed(evt);
            }
        });
        miTipoPersonal.add(miUnidad);

        miCategoria.setText("Categoria");
        miCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCategoriaActionPerformed(evt);
            }
        });
        miTipoPersonal.add(miCategoria);

        miMarca.setText("Marca");
        miMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMarcaActionPerformed(evt);
            }
        });
        miTipoPersonal.add(miMarca);

        jMenuItem1.setText("TipoPersonal");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        miTipoPersonal.add(jMenuItem1);

        miArea.setText("Area");
        miArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAreaActionPerformed(evt);
            }
        });
        miTipoPersonal.add(miArea);

        miAlamcen.setText("Almacen");
        miAlamcen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAlamcenActionPerformed(evt);
            }
        });
        miTipoPersonal.add(miAlamcen);

        miPersonal.setText("Personal");
        miPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPersonalActionPerformed(evt);
            }
        });
        miTipoPersonal.add(miPersonal);

        jMenuItem2.setText("Solicitante");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        miTipoPersonal.add(jMenuItem2);

        jMenuItem3.setText("tipoProductos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        miTipoPersonal.add(jMenuItem3);

        jMenuItem4.setText("Producto");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        miTipoPersonal.add(jMenuItem4);

        jMenuBar1.add(miTipoPersonal);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblNombre)
                .addContainerGap(332, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblNombre)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUnidadActionPerformed
         FormGestionarUnidad form = new FormGestionarUnidad(this,false);
        form.setVisible(true);
    }//GEN-LAST:event_miUnidadActionPerformed

    private void miCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCategoriaActionPerformed
         FormGestionarCategoria form = new FormGestionarCategoria(this,false);
        form.setVisible(true);
    }//GEN-LAST:event_miCategoriaActionPerformed

    private void miMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMarcaActionPerformed
        FormGestionarMarca form = new FormGestionarMarca(this,false);
        form.setVisible(true);
    }//GEN-LAST:event_miMarcaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       FormGestionarTipoPersonal form = new FormGestionarTipoPersonal(this, false);
       form.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void miAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAreaActionPerformed
         FormGestionarArea form = new FormGestionarArea(this, false);
      form.setVisible(true);
    }//GEN-LAST:event_miAreaActionPerformed

    private void miAlamcenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAlamcenActionPerformed
        FormGestionarAlmacen form = new FormGestionarAlmacen(this, false);
       form.setVisible(true);
    }//GEN-LAST:event_miAlamcenActionPerformed

    private void miPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPersonalActionPerformed
        FormGestionarPersonal form = new FormGestionarPersonal(this, false);
       form.setVisible(true);
    }//GEN-LAST:event_miPersonalActionPerformed

    private void miSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalirActionPerformed
       FormLogin form = new FormLogin();
       this.dispose(); 
       form.setVisible(true);
    }//GEN-LAST:event_miSalirActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       FormGestionarSolicitante form = new FormGestionarSolicitante(this,false);
       form.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       FormGestionarTipoProducto form = new FormGestionarTipoProducto(this,false);
       form.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       FormGestionarProducto form = new FormGestionarProducto(this, false);
       form.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
      */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    public static javax.swing.JLabel lblNombre;
    private javax.swing.JMenuItem miAlamcen;
    private javax.swing.JMenuItem miArea;
    private javax.swing.JMenuItem miCategoria;
    private javax.swing.JMenuItem miMarca;
    private javax.swing.JMenuItem miPersonal;
    private javax.swing.JMenuItem miSalir;
    private javax.swing.JMenu miTipoPersonal;
    private javax.swing.JMenuItem miUnidad;
    // End of variables declaration//GEN-END:variables
}
